"""0001

Revision ID: 43195d04fb72
Revises: 
Create Date: 2024-11-28 21:23:22.730973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision: str = '43195d04fb72'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'searchquery',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('value', sa.Text(), server_default=sa.text("''::character varying"), nullable=True),
        sa.Column('doc', sqlalchemy_utils.types.ts_vector.TSVectorType(), server_default=sa.text("''::tsvector"), nullable=True),
        sa.PrimaryKeyConstraint('id', name='searchquery_pkey'),
        sa.UniqueConstraint('value', name='searchquery_value_key')
    )
    op.create_index('searchquery_id_idx', 'searchquery', [sa.text('id ASC NULLS LAST')], unique=False)
    op.create_index('searchquery_id_value_idx', 'searchquery', ['id', 'value'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('searchquery_id_value_idx', table_name='searchquery', postgresql_using='gist')
    op.drop_index('searchquery_id_idx', table_name='searchquery')
    op.drop_table('searchquery')
    # ### end Alembic commands ###
