"""0002

Revision ID: 3caf91993d43
Revises: 43195d04fb72
Create Date: 2025-01-08 19:40:58.167521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3caf91993d43'
down_revision: Union[str, None] = '43195d04fb72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('searchquerydailystat',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('day', sa.Date(), server_default=sa.text("date_trunc('day', now())::date"), nullable=False),
        sa.Column('requests_per_week', sa.Integer(), server_default=sa.text("'0'::int"), nullable=False),
        sa.Column('searchquery_id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(['searchquery_id'], ['searchquery.id'], name='searchquerydailystat_searchquery_id_fkey'),
        sa.PrimaryKeyConstraint('id', 'day', name='searchquerydailystat_pkey'),
        sa.UniqueConstraint('day', 'searchquery_id', name='searchquerydailystat_day_searchquery_id_ukey'),
        postgresql_partition_by='RANGE (day)'
    )
    op.create_index('searchquerydailystat_day_idx', 'searchquerydailystat', [sa.text('day ASC NULLS LAST')], unique=False)
    op.create_index('searchquerydailystat_id_idx', 'searchquerydailystat', [sa.text('id ASC NULLS LAST')], unique=False)
    op.create_index('searchquerydailystat_requests_per_week_day_idx', 'searchquerydailystat', [sa.text('requests_per_week DESC NULLS FIRST'), sa.text('day ASC NULLS LAST')], unique=False)
    op.create_table('searchquerydailystat_tpl',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('day', sa.Date(), server_default=sa.text("date_trunc('day', now())::date"), nullable=False),
        sa.Column('requests_per_week', sa.Integer(), server_default=sa.text("'0'::int"), nullable=False),
        sa.Column('searchquery_id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(['searchquery_id'], ['searchquery.id'], name='searchquerydailystat_tpl_searchquery_id_fkey'),
        sa.PrimaryKeyConstraint('id', 'day', name='searchquerydailystat_tpl_pkey'),
        sa.UniqueConstraint('day', 'searchquery_id', name='searchquerydailystat_tpl_day_searchquery_id_ukey'),
        postgresql_partition_by='RANGE (day)'
    )
    op.create_index('searchquerydailystat_tpl_day_idx', 'searchquerydailystat_tpl', [sa.text('day ASC NULLS LAST')], unique=False)
    op.create_index('searchquerydailystat_tpl_id_idx', 'searchquerydailystat_tpl', [sa.text('id ASC NULLS LAST')], unique=False)
    op.create_index('searchquerydailystat_tpl_requests_per_week_day_idx', 'searchquerydailystat_tpl', [sa.text('requests_per_week DESC NULLS FIRST'), sa.text('day ASC NULLS LAST')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('searchquerydailystat_tpl_requests_per_week_day_idx', table_name='searchquerydailystat_tpl')
    op.drop_index('searchquerydailystat_tpl_id_idx', table_name='searchquerydailystat_tpl')
    op.drop_index('searchquerydailystat_tpl_day_idx', table_name='searchquerydailystat_tpl')
    op.drop_table('searchquerydailystat_tpl')
    op.drop_index('searchquerydailystat_requests_per_week_day_idx', table_name='searchquerydailystat')
    op.drop_index('searchquerydailystat_id_idx', table_name='searchquerydailystat')
    op.drop_index('searchquerydailystat_day_idx', table_name='searchquerydailystat')
    op.drop_table('searchquerydailystat')
    # ### end Alembic commands ###
