"""0003

Revision ID: 82c2132fafd9
Revises: 3caf91993d43
Create Date: 2025-01-23 18:27:21.805694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82c2132fafd9'
down_revision: Union[str, None] = '3caf91993d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('searchquery_doc_idx', 'searchquery', ['doc'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('searchquery_doc_idx', table_name='searchquery', postgresql_using='gin')
    # ### end Alembic commands ###
