"""0004

Revision ID: a3701d0c5d54
Revises: 82c2132fafd9
Create Date: 2025-01-26 14:19:21.262575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3701d0c5d54'
down_revision: Union[str, None] = '82c2132fafd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requeststotalbyday',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('day', sa.Date(), server_default=sa.text("date_trunc('day', now())::date"), nullable=False),
        sa.Column('total_requests_per_week', sa.Integer(), server_default=sa.text("'0'::int"), nullable=False),
        sa.PrimaryKeyConstraint('id', name='requeststotalbyday_pkey'),
        sa.UniqueConstraint('day', name='requeststotalbyday_day_ukey')
    )
    op.create_index('requeststotalbyday_day_idx', 'requeststotalbyday', ['day', sa.text('day ASC NULLS LAST')], unique=False)
    op.create_index('requeststotalbyday_id_idx', 'requeststotalbyday', [sa.text('id ASC NULLS LAST')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('requeststotalbyday_id_idx', table_name='requeststotalbyday')
    op.drop_index('requeststotalbyday_day_idx', table_name='requeststotalbyday')
    op.drop_table('requeststotalbyday')
    # ### end Alembic commands ###
